/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as QueriesIndexRouteImport } from './routes/queries.index'
import { Route as QueriesQueryNameRouteImport } from './routes/queries.$queryName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const QueriesIndexRoute = QueriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueriesRoute,
} as any)
const QueriesQueryNameRoute = QueriesQueryNameRouteImport.update({
  id: '/$queryName',
  path: '/$queryName',
  getParentRoute: () => QueriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/heroes': typeof HeroesRoute
  '/ingest': typeof IngestRoute
  '/matches': typeof MatchesRouteWithChildren
  '/queries': typeof QueriesRouteWithChildren
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/queries/$queryName': typeof QueriesQueryNameRoute
  '/matches/': typeof MatchesIndexRoute
  '/queries/': typeof QueriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/heroes': typeof HeroesRoute
  '/ingest': typeof IngestRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/queries/$queryName': typeof QueriesQueryNameRoute
  '/matches': typeof MatchesIndexRoute
  '/queries': typeof QueriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/heroes': typeof HeroesRoute
  '/ingest': typeof IngestRoute
  '/matches': typeof MatchesRouteWithChildren
  '/queries': typeof QueriesRouteWithChildren
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/queries/$queryName': typeof QueriesQueryNameRoute
  '/matches/': typeof MatchesIndexRoute
  '/queries/': typeof QueriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/heroes'
    | '/ingest'
    | '/matches'
    | '/queries'
    | '/matches/$matchId'
    | '/queries/$queryName'
    | '/matches/'
    | '/queries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/heroes'
    | '/ingest'
    | '/matches/$matchId'
    | '/queries/$queryName'
    | '/matches'
    | '/queries'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/heroes'
    | '/ingest'
    | '/matches'
    | '/queries'
    | '/matches/$matchId'
    | '/queries/$queryName'
    | '/matches/'
    | '/queries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  HeroesRoute: typeof HeroesRoute
  IngestRoute: typeof IngestRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  QueriesRoute: typeof QueriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/queries/': {
      id: '/queries/'
      path: '/'
      fullPath: '/queries/'
      preLoaderRoute: typeof QueriesIndexRouteImport
      parentRoute: typeof QueriesRoute
    }
    '/queries/$queryName': {
      id: '/queries/$queryName'
      path: '/$queryName'
      fullPath: '/queries/$queryName'
      preLoaderRoute: typeof QueriesQueryNameRouteImport
      parentRoute: typeof QueriesRoute
    }
  }
}

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface QueriesRouteChildren {
  QueriesQueryNameRoute: typeof QueriesQueryNameRoute
  QueriesIndexRoute: typeof QueriesIndexRoute
}

const QueriesRouteChildren: QueriesRouteChildren = {
  QueriesQueryNameRoute: QueriesQueryNameRoute,
  QueriesIndexRoute: QueriesIndexRoute,
}

const QueriesRouteWithChildren =
  QueriesRoute._addFileChildren(QueriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  HeroesRoute: HeroesRoute,
  IngestRoute: IngestRoute,
  MatchesRoute: MatchesRouteWithChildren,
  QueriesRoute: QueriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
