/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as IngestRouteImport } from './routes/ingest'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as QueriesRouteImport } from './routes/queries'
import { Route as HealthSamplerRouteImport } from './routes/health.sampler'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as OperationsSamplerRouteImport } from './routes/operations.sampler'
import { Route as QueriesIndexRouteImport } from './routes/queries.index'
import { Route as QueriesQueryNameRouteImport } from './routes/queries.$queryName'
import { Route as ApiSamplerStatusRouteImport } from './routes/api.sampler.status'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches.$matchId.index'
import { Route as MatchesMatchIdCombatRouteImport } from './routes/matches.$matchId.combat'
import { Route as MatchesMatchIdFightsRouteImport } from './routes/matches.$matchId.fights'
import { Route as MatchesMatchIdMapFarmingRouteImport } from './routes/matches.$matchId.map-farming'
import { Route as MatchesMatchIdTimelinesRouteImport } from './routes/matches.$matchId.timelines'
import { Route as MatchesMatchIdFightsIndexRouteImport } from './routes/matches.$matchId.fights.index'
import { Route as MatchesMatchIdFightsFightIdRouteImport } from './routes/matches.$matchId.fights.$fightId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestRoute = IngestRouteImport.update({
  id: '/ingest',
  path: '/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesRoute = QueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthSamplerRoute = HealthSamplerRouteImport.update({
  id: '/sampler',
  path: '/sampler',
  getParentRoute: () => HealthRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const OperationsSamplerRoute = OperationsSamplerRouteImport.update({
  id: '/operations/sampler',
  path: '/operations/sampler',
  getParentRoute: () => rootRouteImport,
} as any)
const QueriesIndexRoute = QueriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QueriesRoute,
} as any)
const QueriesQueryNameRoute = QueriesQueryNameRouteImport.update({
  id: '/$queryName',
  path: '/$queryName',
  getParentRoute: () => QueriesRoute,
} as any)
const ApiSamplerStatusRoute = ApiSamplerStatusRouteImport.update({
  id: '/api/sampler/status',
  path: '/api/sampler/status',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const MatchesMatchIdCombatRoute = MatchesMatchIdCombatRouteImport.update({
  id: '/combat',
  path: '/combat',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const MatchesMatchIdFightsRoute = MatchesMatchIdFightsRouteImport.update({
  id: '/fights',
  path: '/fights',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const MatchesMatchIdMapFarmingRoute =
  MatchesMatchIdMapFarmingRouteImport.update({
    id: '/map-farming',
    path: '/map-farming',
    getParentRoute: () => MatchesMatchIdRoute,
  } as any)
const MatchesMatchIdTimelinesRoute = MatchesMatchIdTimelinesRouteImport.update({
  id: '/timelines',
  path: '/timelines',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const MatchesMatchIdFightsIndexRoute =
  MatchesMatchIdFightsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MatchesMatchIdFightsRoute,
  } as any)
const MatchesMatchIdFightsFightIdRoute =
  MatchesMatchIdFightsFightIdRouteImport.update({
    id: '/$fightId',
    path: '/$fightId',
    getParentRoute: () => MatchesMatchIdFightsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRouteWithChildren
  '/heroes': typeof HeroesRoute
  '/ingest': typeof IngestRoute
  '/matches': typeof MatchesRouteWithChildren
  '/queries': typeof QueriesRouteWithChildren
  '/health/sampler': typeof HealthSamplerRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/operations/sampler': typeof OperationsSamplerRoute
  '/queries/$queryName': typeof QueriesQueryNameRoute
  '/matches/': typeof MatchesIndexRoute
  '/queries/': typeof QueriesIndexRoute
  '/api/sampler/status': typeof ApiSamplerStatusRoute
  '/matches/$matchId/combat': typeof MatchesMatchIdCombatRoute
  '/matches/$matchId/fights': typeof MatchesMatchIdFightsRouteWithChildren
  '/matches/$matchId/map-farming': typeof MatchesMatchIdMapFarmingRoute
  '/matches/$matchId/timelines': typeof MatchesMatchIdTimelinesRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/matches/$matchId/fights/$fightId': typeof MatchesMatchIdFightsFightIdRoute
  '/matches/$matchId/fights/': typeof MatchesMatchIdFightsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRouteWithChildren
  '/heroes': typeof HeroesRoute
  '/ingest': typeof IngestRoute
  '/health/sampler': typeof HealthSamplerRoute
  '/operations/sampler': typeof OperationsSamplerRoute
  '/queries/$queryName': typeof QueriesQueryNameRoute
  '/matches': typeof MatchesIndexRoute
  '/queries': typeof QueriesIndexRoute
  '/api/sampler/status': typeof ApiSamplerStatusRoute
  '/matches/$matchId/combat': typeof MatchesMatchIdCombatRoute
  '/matches/$matchId/map-farming': typeof MatchesMatchIdMapFarmingRoute
  '/matches/$matchId/timelines': typeof MatchesMatchIdTimelinesRoute
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/matches/$matchId/fights/$fightId': typeof MatchesMatchIdFightsFightIdRoute
  '/matches/$matchId/fights': typeof MatchesMatchIdFightsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRouteWithChildren
  '/heroes': typeof HeroesRoute
  '/ingest': typeof IngestRoute
  '/matches': typeof MatchesRouteWithChildren
  '/queries': typeof QueriesRouteWithChildren
  '/health/sampler': typeof HealthSamplerRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/operations/sampler': typeof OperationsSamplerRoute
  '/queries/$queryName': typeof QueriesQueryNameRoute
  '/matches/': typeof MatchesIndexRoute
  '/queries/': typeof QueriesIndexRoute
  '/api/sampler/status': typeof ApiSamplerStatusRoute
  '/matches/$matchId/combat': typeof MatchesMatchIdCombatRoute
  '/matches/$matchId/fights': typeof MatchesMatchIdFightsRouteWithChildren
  '/matches/$matchId/map-farming': typeof MatchesMatchIdMapFarmingRoute
  '/matches/$matchId/timelines': typeof MatchesMatchIdTimelinesRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/matches/$matchId/fights/$fightId': typeof MatchesMatchIdFightsFightIdRoute
  '/matches/$matchId/fights/': typeof MatchesMatchIdFightsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/heroes'
    | '/ingest'
    | '/matches'
    | '/queries'
    | '/health/sampler'
    | '/matches/$matchId'
    | '/operations/sampler'
    | '/queries/$queryName'
    | '/matches/'
    | '/queries/'
    | '/api/sampler/status'
    | '/matches/$matchId/combat'
    | '/matches/$matchId/fights'
    | '/matches/$matchId/map-farming'
    | '/matches/$matchId/timelines'
    | '/matches/$matchId/'
    | '/matches/$matchId/fights/$fightId'
    | '/matches/$matchId/fights/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/heroes'
    | '/ingest'
    | '/health/sampler'
    | '/operations/sampler'
    | '/queries/$queryName'
    | '/matches'
    | '/queries'
    | '/api/sampler/status'
    | '/matches/$matchId/combat'
    | '/matches/$matchId/map-farming'
    | '/matches/$matchId/timelines'
    | '/matches/$matchId'
    | '/matches/$matchId/fights/$fightId'
    | '/matches/$matchId/fights'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/heroes'
    | '/ingest'
    | '/matches'
    | '/queries'
    | '/health/sampler'
    | '/matches/$matchId'
    | '/operations/sampler'
    | '/queries/$queryName'
    | '/matches/'
    | '/queries/'
    | '/api/sampler/status'
    | '/matches/$matchId/combat'
    | '/matches/$matchId/fights'
    | '/matches/$matchId/map-farming'
    | '/matches/$matchId/timelines'
    | '/matches/$matchId/'
    | '/matches/$matchId/fights/$fightId'
    | '/matches/$matchId/fights/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRouteWithChildren
  HeroesRoute: typeof HeroesRoute
  IngestRoute: typeof IngestRoute
  MatchesRoute: typeof MatchesRouteWithChildren
  QueriesRoute: typeof QueriesRouteWithChildren
  OperationsSamplerRoute: typeof OperationsSamplerRoute
  ApiSamplerStatusRoute: typeof ApiSamplerStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest': {
      id: '/ingest'
      path: '/ingest'
      fullPath: '/ingest'
      preLoaderRoute: typeof IngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries': {
      id: '/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof QueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/sampler': {
      id: '/health/sampler'
      path: '/sampler'
      fullPath: '/health/sampler'
      preLoaderRoute: typeof HealthSamplerRouteImport
      parentRoute: typeof HealthRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/operations/sampler': {
      id: '/operations/sampler'
      path: '/operations/sampler'
      fullPath: '/operations/sampler'
      preLoaderRoute: typeof OperationsSamplerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queries/': {
      id: '/queries/'
      path: '/'
      fullPath: '/queries/'
      preLoaderRoute: typeof QueriesIndexRouteImport
      parentRoute: typeof QueriesRoute
    }
    '/queries/$queryName': {
      id: '/queries/$queryName'
      path: '/$queryName'
      fullPath: '/queries/$queryName'
      preLoaderRoute: typeof QueriesQueryNameRouteImport
      parentRoute: typeof QueriesRoute
    }
    '/api/sampler/status': {
      id: '/api/sampler/status'
      path: '/api/sampler/status'
      fullPath: '/api/sampler/status'
      preLoaderRoute: typeof ApiSamplerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/combat': {
      id: '/matches/$matchId/combat'
      path: '/combat'
      fullPath: '/matches/$matchId/combat'
      preLoaderRoute: typeof MatchesMatchIdCombatRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/fights': {
      id: '/matches/$matchId/fights'
      path: '/fights'
      fullPath: '/matches/$matchId/fights'
      preLoaderRoute: typeof MatchesMatchIdFightsRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/map-farming': {
      id: '/matches/$matchId/map-farming'
      path: '/map-farming'
      fullPath: '/matches/$matchId/map-farming'
      preLoaderRoute: typeof MatchesMatchIdMapFarmingRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/timelines': {
      id: '/matches/$matchId/timelines'
      path: '/timelines'
      fullPath: '/matches/$matchId/timelines'
      preLoaderRoute: typeof MatchesMatchIdTimelinesRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/fights/': {
      id: '/matches/$matchId/fights/'
      path: '/'
      fullPath: '/matches/$matchId/fights/'
      preLoaderRoute: typeof MatchesMatchIdFightsIndexRouteImport
      parentRoute: typeof MatchesMatchIdFightsRoute
    }
    '/matches/$matchId/fights/$fightId': {
      id: '/matches/$matchId/fights/$fightId'
      path: '/$fightId'
      fullPath: '/matches/$matchId/fights/$fightId'
      preLoaderRoute: typeof MatchesMatchIdFightsFightIdRouteImport
      parentRoute: typeof MatchesMatchIdFightsRoute
    }
  }
}

interface HealthRouteChildren {
  HealthSamplerRoute: typeof HealthSamplerRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthSamplerRoute: HealthSamplerRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

interface MatchesMatchIdFightsRouteChildren {
  MatchesMatchIdFightsFightIdRoute: typeof MatchesMatchIdFightsFightIdRoute
  MatchesMatchIdFightsIndexRoute: typeof MatchesMatchIdFightsIndexRoute
}

const MatchesMatchIdFightsRouteChildren: MatchesMatchIdFightsRouteChildren = {
  MatchesMatchIdFightsFightIdRoute: MatchesMatchIdFightsFightIdRoute,
  MatchesMatchIdFightsIndexRoute: MatchesMatchIdFightsIndexRoute,
}

const MatchesMatchIdFightsRouteWithChildren =
  MatchesMatchIdFightsRoute._addFileChildren(MatchesMatchIdFightsRouteChildren)

interface MatchesMatchIdRouteChildren {
  MatchesMatchIdCombatRoute: typeof MatchesMatchIdCombatRoute
  MatchesMatchIdFightsRoute: typeof MatchesMatchIdFightsRouteWithChildren
  MatchesMatchIdMapFarmingRoute: typeof MatchesMatchIdMapFarmingRoute
  MatchesMatchIdTimelinesRoute: typeof MatchesMatchIdTimelinesRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

const MatchesMatchIdRouteChildren: MatchesMatchIdRouteChildren = {
  MatchesMatchIdCombatRoute: MatchesMatchIdCombatRoute,
  MatchesMatchIdFightsRoute: MatchesMatchIdFightsRouteWithChildren,
  MatchesMatchIdMapFarmingRoute: MatchesMatchIdMapFarmingRoute,
  MatchesMatchIdTimelinesRoute: MatchesMatchIdTimelinesRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}

const MatchesMatchIdRouteWithChildren = MatchesMatchIdRoute._addFileChildren(
  MatchesMatchIdRouteChildren,
)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRouteWithChildren
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRouteWithChildren,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface QueriesRouteChildren {
  QueriesQueryNameRoute: typeof QueriesQueryNameRoute
  QueriesIndexRoute: typeof QueriesIndexRoute
}

const QueriesRouteChildren: QueriesRouteChildren = {
  QueriesQueryNameRoute: QueriesQueryNameRoute,
  QueriesIndexRoute: QueriesIndexRoute,
}

const QueriesRouteWithChildren =
  QueriesRoute._addFileChildren(QueriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRouteWithChildren,
  HeroesRoute: HeroesRoute,
  IngestRoute: IngestRoute,
  MatchesRoute: MatchesRouteWithChildren,
  QueriesRoute: QueriesRouteWithChildren,
  OperationsSamplerRoute: OperationsSamplerRoute,
  ApiSamplerStatusRoute: ApiSamplerStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
